PRAGMA FOREIGN_KEYS = off;
BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(45) NOT NULL,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS game (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS gameResult (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    result INTEGER NOT NULL,
    score INTEGER NOT NULL,
    nameId INTEGER,
    userId INTEGER,
    FOREIGN_KEYS (
        nameId
    ) REFERENCES user (id),
    FOREIGN_KEYS (
        userId
    ) REFERENCES user (id)
);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;