PRAGMA FOREIGN_KEYS = off;
BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS role (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(45) NOT NULL,
    password VARCHAR(100) NOT NULL,
    roleId INTEGER,
    email VARCHAR(80),
    countryCode VARCHAR(10),
    personalised INTEGER NOT NULL,
    FOREIGN KEY (roleId) REFERENCES role (id)
);

CREATE TABLE IF NOT EXISTS game (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS gameResult (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    result INTEGER NOT NULL,
    score INTEGER NOT NULL,
    nameId INTEGER,
    userId INTEGER,
    FOREIGN KEY (nameId) REFERENCES game (id),
    FOREIGN KEY (userId) REFERENCES user (id) 
);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;